version: '3.8'

services:
  app:
    image: galeria-app:latest  # Nome da imagem do aplicativo Spring Boot
    container_name: galeria-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Porta exposta para acessar a aplicação
    environment:
      # Configurações para o MySQL
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bdgaleria  # Nome do serviço MySQL no Docker Compose
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      - mysql  # Aguarda o MySQL estar disponível
    restart: always  # Reinicia automaticamente o contêiner em caso de falha

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"  # Porta exposta para conexões externas
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_DATABASE: bdgaleria
        MYSQL_USER: mysql_user
        MYSQL_PASSWORD: mysql_password
    volumes:
      - mysql_data:/var/lib/mysql  # Persistência de dados
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always  # Reinicia automaticamente o contêiner em caso de falha

volumes:
  mysql_data:  # Volume para o banco de dados
