version: '3.8'

services:
  app:
    image: galeria-app:latest  # Nome da imagem do aplicativo Spring Boot
    container_name: galeria-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Porta exposta para acessar a aplicação
    environment:
      # Configurações para o MySQL
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bdgaleria  # Nome do serviço MySQL no Docker Compose
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      - mysql  # Aguarda o MySQL estar disponível
      - rabbitmq  # Aguarda o RabbitMQ estar disponível
    restart: always  # Reinicia automaticamente o contêiner em caso de falha
